# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'TimeTableProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TimeTableProject
  pod "RxSwift"
  pod 'Firebase/Core'
  pod 'Alamofire' , '~> 4.8.1'
  pod 'RealmSwift'
end
